version: "3.8"

services:
  db:
    image: mariadb:10.6
    container_name: mytube-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=terry8473   # ğŸ‘‰ ì‹¤ì œ ë¹„ë°€ë²ˆí˜¸ ì…ë ¥
      - MYSQL_DATABASE=mytubedb
    ports:
      - "3307:3306"  # í˜¸ìŠ¤íŠ¸ 3307 â†’ ì»¨í…Œì´ë„ˆ 3306
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: mytube-redis
    ports:
      - "6379:6379"
    restart: always

  backend:
    build:
      context: ./backend/demo   # Spring Boot í”„ë¡œì íŠ¸ ìœ„ì¹˜
      dockerfile: Dockerfile
    image: mytube-backend:latest
    container_name: mytube-backend
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/mytubedb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=yourpassword
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: mytube-frontend:latest
    container_name: mytube-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  db_data:
